In [9]:
import open3d as o3d
import numpy as np


def main():
    #sample_pcd = o3d.data.PCDPointCloud()
    #pcd = o3d.io.read_point_cloud(sample_pcd.path)
    #o3d.visualization.draw([pcd])
    #sample_pcd = o3d.data.PCDPointCloud()
    pcd = o3d.io.read_point_cloud("test.pcd")
    #o3d.visualization.draw([pcd])
    o3d.visualization.draw_geometries([pcd])

if __name__ == "__main__":
    main()

[Open3D WARNING] [ViewControl] SetViewPoint() failed because window height and width are not set.


In [4]:
pcd = o3d.io.read_point_cloud("test.pcd")

In [6]:
type(pcd)

open3d.cpu.pybind.geometry.PointCloud

In [7]:
print(pcd)

PointCloud with 110678 points.


In [8]:
print(np.asarray(pcd.points))

[[1.        2.        3.       ]
 [7.0517383 7.415863  1.7076385]
 [7.0715866 7.4176059 1.705902 ]
 ...
 [7.0193615 7.4431338 1.7104712]
 [7.0219693 7.4232097 1.7202811]
 [7.0327621 7.4141197 1.719337 ]]


In [10]:
len(np.asarray(pcd.points))

110678

In [11]:
type(np.asarray(pcd.points))

numpy.ndarray